// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	TEST_KV: KVNamespace;
	DO: DurableObjectNamespace<import("./api/index").ThingsDO>;
	TEST_DO: DurableObjectNamespace<import("./api/index").TestDurableObject>;
	BROWSER_DO: DurableObjectNamespace<import("./api/index").Browser>;
	OBS_BROADCASTER: DurableObjectNamespace<import("./api/index").ObservabilityBroadcaster>;
	AI: Ai;
	ASSETS: Fetcher;
}
