// Generated by Wrangler by running `wrangler types worker.d.ts -c wrangler.jsonc`

interface Env {
	KV: KVNamespace;
	TEST_KV: KVNamespace;
	DO: DurableObjectNamespace /* DurableObject */;
	TEST_DO: DurableObjectNamespace /* TestDurableObject */;
	ASSETS: Fetcher;
}
