/**
 * @dotdo/search - Unified search compat layer
 *
 * Re-exports all vector and fulltext search adapters from a single entry point.
 * Each adapter provides API-compatible implementations backed by Durable Objects.
 */

// =============================================================================
// Vector Database Adapters
// =============================================================================

// Chroma - Vector database with embedding functions
export {
  ChromaClient,
  _resetStorage as chromaResetStorage,
  _getStorageStats as chromaGetStorageStats,
  ChromaError,
  ChromaConfigurationError,
  ChromaConnectionError,
  ChromaNotFoundError,
  ChromaConflictError,
  ChromaValidationError,
  ChromaRequestError,
} from './vector/chroma'

export type {
  ChromaClientParams,
  AuthOptions as ChromaAuthOptions,
  MetadataValue as ChromaMetadataValue,
  Metadata as ChromaMetadata,
  Embedding as ChromaEmbedding,
  Embeddings as ChromaEmbeddings,
  WhereOperators as ChromaWhereOperators,
  WhereLogicalOperators as ChromaWhereLogicalOperators,
  Where as ChromaWhere,
  WhereDocumentOperators as ChromaWhereDocumentOperators,
  WhereDocumentLogicalOperators as ChromaWhereDocumentLogicalOperators,
  WhereDocument as ChromaWhereDocument,
  IncludeEnum as ChromaIncludeEnum,
  CollectionModel as ChromaCollectionModel,
  CreateCollectionParams as ChromaCreateCollectionParams,
  GetCollectionParams as ChromaGetCollectionParams,
  DeleteCollectionParams as ChromaDeleteCollectionParams,
  ModifyCollectionParams as ChromaModifyCollectionParams,
  AddParams as ChromaAddParams,
  UpdateParams as ChromaUpdateParams,
  UpsertParams as ChromaUpsertParams,
  QueryParams as ChromaQueryParams,
  QueryResponse as ChromaQueryResponse,
  GetParams as ChromaGetParams,
  GetResponse as ChromaGetResponse,
  DeleteParams as ChromaDeleteParams,
  PeekParams as ChromaPeekParams,
  EmbeddingFunction as ChromaEmbeddingFunction,
  Collection as ChromaCollection,
  ChromaClientInterface,
} from './vector/chroma'

// Pinecone - Serverless vector database
export {
  Pinecone,
  _resetStorage as pineconeResetStorage,
  _getStorageStats as pineconeGetStorageStats,
  PineconeError,
  PineconeConfigurationError,
  PineconeConnectionError,
  PineconeNotFoundError,
  PineconeConflictError,
  PineconeValidationError,
  PineconeRequestError,
} from './vector/pinecone'

export type {
  PineconeConfiguration,
  ExtendedPineconeConfiguration,
  IndexModel as PineconeIndexModel,
  IndexList as PineconeIndexList,
  CreateIndexOptions as PineconeCreateIndexOptions,
  ConfigureIndexOptions as PineconeConfigureIndexOptions,
  Metric as PineconeMetric,
  PodType as PineconePodType,
  IndexStatus as PineconeIndexStatus,
  DeletionProtection as PineconeDeletionProtection,
  Cloud as PineconeCloud,
  ServerlessSpec as PineconeServerlessSpec,
  PodSpec as PineconePodSpec,
  IndexSpec as PineconeIndexSpec,
  IndexStatusDetails as PineconeIndexStatusDetails,
  RecordValues as PineconeRecordValues,
  RecordSparseValues as PineconeRecordSparseValues,
  RecordMetadata as PineconeRecordMetadata,
  RecordMetadataValue as PineconeRecordMetadataValue,
  PineconeRecord,
  ScoredPineconeRecord,
  MetadataFilter as PineconeMetadataFilter,
  MetadataFilterOperators as PineconeMetadataFilterOperators,
  QueryOptions as PineconeQueryOptions,
  QueryResponse as PineconeQueryResponse,
  UpsertResponse as PineconeUpsertResponse,
  FetchResponse as PineconeFetchResponse,
  DeleteOptions as PineconeDeleteOptions,
  DeleteResponse as PineconeDeleteResponse,
  UpdateOptions as PineconeUpdateOptions,
  UpdateResponse as PineconeUpdateResponse,
  ListOptions as PineconeListOptions,
  ListResponse as PineconeListResponse,
  VectorId as PineconeVectorId,
  NamespaceStats as PineconeNamespaceStats,
  IndexStats as PineconeIndexStats,
  DescribeIndexStatsResponse as PineconeDescribeIndexStatsResponse,
  CollectionStatus as PineconeCollectionStatus,
  CollectionModel as PineconeCollectionModel,
  CreateCollectionOptions as PineconeCreateCollectionOptions,
  CollectionList as PineconeCollectionList,
  IndexNamespace as PineconeIndexNamespace,
  Index as PineconeIndex,
  PineconeClient,
} from './vector/pinecone'

// Qdrant - Vector similarity search engine
export { QdrantClient } from './vector/qdrant'

export type {
  QdrantClientConfig,
  Distance as QdrantDistance,
  VectorParams as QdrantVectorParams,
  HnswConfig as QdrantHnswConfig,
  QuantizationConfig as QdrantQuantizationConfig,
  CollectionConfig as QdrantCollectionConfig,
  CollectionInfo as QdrantCollectionInfo,
  PayloadSchemaInfo as QdrantPayloadSchemaInfo,
  CollectionsResponse as QdrantCollectionsResponse,
  PointId as QdrantPointId,
  Payload as QdrantPayload,
  PointStruct as QdrantPointStruct,
  Record as QdrantRecord,
  ScoredPoint as QdrantScoredPoint,
  FieldCondition as QdrantFieldCondition,
  MatchValue as QdrantMatchValue,
  RangeCondition as QdrantRangeCondition,
  GeoBoundingBox as QdrantGeoBoundingBox,
  GeoRadius as QdrantGeoRadius,
  GeoPolygon as QdrantGeoPolygon,
  GeoPoint as QdrantGeoPoint,
  ValuesCount as QdrantValuesCount,
  HasIdCondition as QdrantHasIdCondition,
  IsEmptyCondition as QdrantIsEmptyCondition,
  IsNullCondition as QdrantIsNullCondition,
  NestedCondition as QdrantNestedCondition,
  Condition as QdrantCondition,
  Filter as QdrantFilter,
  SearchRequest as QdrantSearchRequest,
  SearchParams as QdrantSearchParams,
  RetrieveRequest as QdrantRetrieveRequest,
  ScrollRequest as QdrantScrollRequest,
  ScrollResponse as QdrantScrollResponse,
  CountRequest as QdrantCountRequest,
  CountResponse as QdrantCountResponse,
  PointsSelector as QdrantPointsSelector,
  UpsertRequest as QdrantUpsertRequest,
  OperationResult as QdrantOperationResult,
  BatchSearchRequest as QdrantBatchSearchRequest,
  RecommendRequest as QdrantRecommendRequest,
} from './vector/qdrant'

// Weaviate - AI-native vector database
export { weaviate, WeaviateClient } from './vector/weaviate'

export type {
  WeaviateClientConfig,
  WeaviateClass,
  WeaviateSchema,
  WeaviateProperty,
  WeaviateDataType,
  WeaviateVectorizer,
  VectorIndexConfig as WeaviateVectorIndexConfig,
  InvertedIndexConfig as WeaviateInvertedIndexConfig,
  WeaviateObject,
  WeaviateAdditional,
  NearVectorParams as WeaviateNearVectorParams,
  NearTextParams as WeaviateNearTextParams,
  NearObjectParams as WeaviateNearObjectParams,
  Bm25Params as WeaviateBm25Params,
  HybridParams as WeaviateHybridParams,
  WhereFilter as WeaviateWhereFilter,
  WhereOperator as WeaviateWhereOperator,
  SortSpec as WeaviateSortSpec,
  GraphQLResponse as WeaviateGraphQLResponse,
  BatchResult as WeaviateBatchResult,
  BatchDeleteResult as WeaviateBatchDeleteResult,
} from './vector/weaviate'

// =============================================================================
// Full-Text Search Adapters
// =============================================================================

// Elasticsearch - Distributed search and analytics
export {
  Client as ElasticsearchClient,
  clearAllIndices as elasticsearchClearAllIndices,
  ElasticsearchError,
  DocumentNotFoundError as ElasticsearchDocumentNotFoundError,
  IndexNotFoundError as ElasticsearchIndexNotFoundError,
  IndexAlreadyExistsError as ElasticsearchIndexAlreadyExistsError,
  VersionConflictError as ElasticsearchVersionConflictError,
  ValidationError as ElasticsearchValidationError,
} from './fulltext/elasticsearch'

export type {
  ClientOptions as ElasticsearchClientOptions,
  ClientType as ElasticsearchClientType,
  IndicesClient as ElasticsearchIndicesClient,
  ClusterClient as ElasticsearchClusterClient,
  InfoResponse as ElasticsearchInfoResponse,
  IndexRequest as ElasticsearchIndexRequest,
  IndexResponse as ElasticsearchIndexResponse,
  GetRequest as ElasticsearchGetRequest,
  GetResponse as ElasticsearchGetResponse,
  MgetRequest as ElasticsearchMgetRequest,
  MgetResponse as ElasticsearchMgetResponse,
  DeleteRequest as ElasticsearchDeleteRequest,
  DeleteResponse as ElasticsearchDeleteResponse,
  UpdateRequest as ElasticsearchUpdateRequest,
  UpdateResponse as ElasticsearchUpdateResponse,
  DeleteByQueryRequest as ElasticsearchDeleteByQueryRequest,
  DeleteByQueryResponse as ElasticsearchDeleteByQueryResponse,
  UpdateByQueryRequest as ElasticsearchUpdateByQueryRequest,
  UpdateByQueryResponse as ElasticsearchUpdateByQueryResponse,
  BulkAction as ElasticsearchBulkAction,
  BulkRequest as ElasticsearchBulkRequest,
  BulkResponse as ElasticsearchBulkResponse,
  BulkResponseItem as ElasticsearchBulkResponseItem,
  SearchRequest as ElasticsearchSearchRequest,
  SearchResponse as ElasticsearchSearchResponse,
  SearchHit as ElasticsearchSearchHit,
  CountRequest as ElasticsearchCountRequest,
  CountResponse as ElasticsearchCountResponse,
  ScrollRequest as ElasticsearchScrollRequest,
  ClearScrollRequest as ElasticsearchClearScrollRequest,
  ClearScrollResponse as ElasticsearchClearScrollResponse,
  QueryDsl as ElasticsearchQueryDsl,
  AggregationDsl as ElasticsearchAggregationDsl,
  AggregationResult as ElasticsearchAggregationResult,
  AggregationBucket as ElasticsearchAggregationBucket,
  SortOption as ElasticsearchSortOption,
  SourceFilter as ElasticsearchSourceFilter,
  HighlightOptions as ElasticsearchHighlightOptions,
  IndicesCreateRequest as ElasticsearchIndicesCreateRequest,
  IndicesCreateResponse as ElasticsearchIndicesCreateResponse,
  IndicesDeleteRequest as ElasticsearchIndicesDeleteRequest,
  IndicesDeleteResponse as ElasticsearchIndicesDeleteResponse,
  IndicesExistsRequest as ElasticsearchIndicesExistsRequest,
  IndicesGetRequest as ElasticsearchIndicesGetRequest,
  IndicesGetResponse as ElasticsearchIndicesGetResponse,
  IndicesGetMappingRequest as ElasticsearchIndicesGetMappingRequest,
  IndicesGetMappingResponse as ElasticsearchIndicesGetMappingResponse,
  IndicesPutMappingRequest as ElasticsearchIndicesPutMappingRequest,
  IndicesPutMappingResponse as ElasticsearchIndicesPutMappingResponse,
  IndicesGetSettingsRequest as ElasticsearchIndicesGetSettingsRequest,
  IndicesGetSettingsResponse as ElasticsearchIndicesGetSettingsResponse,
  IndicesPutSettingsRequest as ElasticsearchIndicesPutSettingsRequest,
  IndicesPutSettingsResponse as ElasticsearchIndicesPutSettingsResponse,
  IndicesRefreshRequest as ElasticsearchIndicesRefreshRequest,
  IndicesRefreshResponse as ElasticsearchIndicesRefreshResponse,
  IndicesStatsRequest as ElasticsearchIndicesStatsRequest,
  IndicesStatsResponse as ElasticsearchIndicesStatsResponse,
  IndicesUpdateAliasesRequest as ElasticsearchIndicesUpdateAliasesRequest,
  IndicesUpdateAliasesResponse as ElasticsearchIndicesUpdateAliasesResponse,
  IndicesGetAliasRequest as ElasticsearchIndicesGetAliasRequest,
  IndicesGetAliasResponse as ElasticsearchIndicesGetAliasResponse,
  IndicesFlushRequest as ElasticsearchIndicesFlushRequest,
  IndicesFlushResponse as ElasticsearchIndicesFlushResponse,
  AliasAction as ElasticsearchAliasAction,
  IndexMappings as ElasticsearchIndexMappings,
  IndexSettings as ElasticsearchIndexSettings,
  MappingProperty as ElasticsearchMappingProperty,
  ClusterHealthRequest as ElasticsearchClusterHealthRequest,
  ClusterHealthResponse as ElasticsearchClusterHealthResponse,
} from './fulltext/elasticsearch'

// Typesense - Open-source typo-tolerant search
export {
  clearAllCollections as typesenseClearAllCollections,
  TypesenseError,
  ObjectNotFound as TypesenseObjectNotFound,
  ObjectAlreadyExists as TypesenseObjectAlreadyExists,
  ObjectUnprocessable as TypesenseObjectUnprocessable,
  RequestMalformed as TypesenseRequestMalformed,
  RequestUnauthorized as TypesenseRequestUnauthorized,
  ServerError as TypesenseServerError,
  MissingConfigurationError as TypesenseMissingConfigurationError,
} from './fulltext/typesense'

export { default as Typesense } from './fulltext/typesense'

export type {
  FieldType as TypesenseFieldType,
  Field as TypesenseField,
  CollectionSchema as TypesenseCollectionSchema,
  Collection as TypesenseCollection,
  CollectionUpdateSchema as TypesenseCollectionUpdateSchema,
  Document as TypesenseDocument,
  IndexedDocument as TypesenseIndexedDocument,
  ImportResponse as TypesenseImportResponse,
  ExportOptions as TypesenseExportOptions,
  SearchParams as TypesenseSearchParams,
  SearchHighlight as TypesenseSearchHighlight,
  SearchHit as TypesenseSearchHit,
  FacetCount as TypesenseFacetCount,
  FacetStats as TypesenseFacetStats,
  FacetResult as TypesenseFacetResult,
  SearchResult as TypesenseSearchResult,
  MultiSearchRequest as TypesenseMultiSearchRequest,
  MultiSearchResult as TypesenseMultiSearchResult,
  GeoPoint as TypesenseGeoPoint,
  GeoDistanceUnit as TypesenseGeoDistanceUnit,
  NodeConfiguration as TypesenseNodeConfiguration,
  ClientConfig as TypesenseClientConfig,
  DocumentsApi as TypesenseDocumentsApi,
  DocumentApi as TypesenseDocumentApi,
  CollectionApi as TypesenseCollectionApi,
  CollectionsApi as TypesenseCollectionsApi,
  TypesenseClient,
} from './fulltext/typesense'

// Algolia - Search & discovery platform
export {
  algoliasearch,
  clearAllIndices as algoliaClearAllIndices,
  AlgoliaError,
  ObjectNotFoundError as AlgoliaObjectNotFoundError,
  IndexNotFoundError as AlgoliaIndexNotFoundError,
  InvalidFilterError as AlgoliaInvalidFilterError,
} from './fulltext/algolia'

export { default as algolia } from './fulltext/algolia'

export type {
  Hit as AlgoliaHit,
  SearchHit as AlgoliaSearchHit,
  HighlightResult as AlgoliaHighlightResult,
  SnippetResult as AlgoliaSnippetResult,
  RankingInfo as AlgoliaRankingInfo,
  FacetHit as AlgoliaFacetHit,
  FacetStats as AlgoliaFacetStats,
  Facets as AlgoliaFacets,
  FacetsStats as AlgoliaFacetsStats,
  SearchOptions as AlgoliaSearchOptions,
  BrowseOptions as AlgoliaBrowseOptions,
  SearchForFacetValuesOptions as AlgoliaSearchForFacetValuesOptions,
  SearchResponse as AlgoliaSearchResponse,
  BrowseResponse as AlgoliaBrowseResponse,
  SearchForFacetValuesResponse as AlgoliaSearchForFacetValuesResponse,
  AlgoliaObject,
  SaveObjectResponse as AlgoliaSaveObjectResponse,
  SaveObjectsResponse as AlgoliaSaveObjectsResponse,
  DeleteObjectResponse as AlgoliaDeleteObjectResponse,
  DeleteObjectsResponse as AlgoliaDeleteObjectsResponse,
  GetObjectOptions as AlgoliaGetObjectOptions,
  GetObjectsOptions as AlgoliaGetObjectsOptions,
  GetObjectsResponse as AlgoliaGetObjectsResponse,
  PartialUpdateObjectOptions as AlgoliaPartialUpdateObjectOptions,
  ClearObjectsResponse as AlgoliaClearObjectsResponse,
  Settings as AlgoliaSettings,
  SetSettingsOptions as AlgoliaSetSettingsOptions,
  GetSettingsResponse as AlgoliaGetSettingsResponse,
  TaskResponse as AlgoliaTaskResponse,
  IndexInfo as AlgoliaIndexInfo,
  ListIndicesResponse as AlgoliaListIndicesResponse,
  CopyIndexOptions as AlgoliaCopyIndexOptions,
  CopyMoveIndexResponse as AlgoliaCopyMoveIndexResponse,
  ClientOptions as AlgoliaClientOptions,
  MultipleQueriesQuery as AlgoliaMultipleQueriesQuery,
  MultipleQueriesResponse as AlgoliaMultipleQueriesResponse,
  SearchIndex as AlgoliaSearchIndex,
  SearchClient as AlgoliaSearchClient,
} from './fulltext/algolia'

// Meilisearch - Lightning fast search engine
export {
  MeiliSearch,
  clearAllIndices as meilisearchClearAllIndices,
  MeiliSearchError,
  DocumentNotFoundError as MeiliSearchDocumentNotFoundError,
  IndexNotFoundError as MeiliSearchIndexNotFoundError,
  TaskTimeoutError as MeiliSearchTaskTimeoutError,
  InvalidFilterError as MeiliSearchInvalidFilterError,
} from './fulltext/meilisearch'

export { default as meilisearch } from './fulltext/meilisearch'

export type {
  Config as MeiliSearchConfig,
  Health as MeiliSearchHealth,
  Version as MeiliSearchVersion,
  Stats as MeiliSearchStats,
  IndexOptions as MeiliSearchIndexOptions,
  IndexObject as MeiliSearchIndexObject,
  IndexStats as MeiliSearchIndexStats,
  IndexesResults as MeiliSearchIndexesResults,
  IndexesQuery as MeiliSearchIndexesQuery,
  Document as MeiliSearchDocument,
  DocumentsQuery as MeiliSearchDocumentsQuery,
  DocumentQuery as MeiliSearchDocumentQuery,
  DocumentsResults as MeiliSearchDocumentsResults,
  DeleteDocumentsQuery as MeiliSearchDeleteDocumentsQuery,
  DocumentsOptions as MeiliSearchDocumentsOptions,
  SearchParams as MeiliSearchSearchParams,
  SearchResponse as MeiliSearchSearchResponse,
  Hit as MeiliSearchHit,
  MatchPosition as MeiliSearchMatchPosition,
  FacetDistribution as MeiliSearchFacetDistribution,
  FacetStats as MeiliSearchFacetStats,
  MultiSearchQuery as MeiliSearchMultiSearchQuery,
  MultiSearchRequest as MeiliSearchMultiSearchRequest,
  MultiSearchResponse as MeiliSearchMultiSearchResponse,
  HybridSearch as MeiliSearchHybridSearch,
  Settings as MeiliSearchSettings,
  TypoTolerance as MeiliSearchTypoTolerance,
  Pagination as MeiliSearchPagination,
  Faceting as MeiliSearchFaceting,
  TaskStatus as MeiliSearchTaskStatus,
  TaskType as MeiliSearchTaskType,
  EnqueuedTask as MeiliSearchEnqueuedTask,
  Task as MeiliSearchTask,
  TaskDetails as MeiliSearchTaskDetails,
  TaskError as MeiliSearchTaskError,
  TasksQuery as MeiliSearchTasksQuery,
  TasksResults as MeiliSearchTasksResults,
  WaitOptions as MeiliSearchWaitOptions,
  CancelTasksQuery as MeiliSearchCancelTasksQuery,
  Key as MeiliSearchKey,
  KeyCreation as MeiliSearchKeyCreation,
  KeyUpdate as MeiliSearchKeyUpdate,
  KeysQuery as MeiliSearchKeysQuery,
  KeysResults as MeiliSearchKeysResults,
  SwapIndexesParams as MeiliSearchSwapIndexesParams,
  Index as MeiliSearchIndex,
  MeiliSearchClient,
} from './fulltext/meilisearch'

// Orama - Fast full-text search engine
export {
  create as oramaCreate,
  insert as oramaInsert,
  insertMultiple as oramaInsertMultiple,
  remove as oramaRemove,
  update as oramaUpdate,
  search as oramaSearch,
  count as oramaCount,
  getByID as oramaGetByID,
} from './fulltext/orama'

export type {
  Schema as OramaSchema,
  SchemaFieldType as OramaSchemaFieldType,
  Document as OramaDocument,
  OramaConfig,
  Orama,
  SearchParams as OramaSearchParams,
  SearchResult as OramaSearchResult,
  SearchHit as OramaSearchHit,
  WhereFilter as OramaWhereFilter,
  WhereOperator as OramaWhereOperator,
} from './fulltext/orama'
