/**
 * @dotdo/slack - Slack SDK Compatibility Layer
 *
 * Drop-in replacement for @slack/web-api with edge runtime support.
 *
 * @example
 * ```typescript
 * import { WebClient } from '@dotdo/slack'
 *
 * const client = new WebClient('xoxb-token')
 *
 * // Post a message
 * const result = await client.chat.postMessage({
 *   channel: 'C1234567890',
 *   text: 'Hello, World!',
 * })
 *
 * // Get channel history
 * const history = await client.conversations.history({
 *   channel: 'C1234567890',
 *   limit: 10,
 * })
 * ```
 *
 * @module @dotdo/slack
 */

// Re-export from client
export {
  WebClient,
  SlackError,
  type WebClientOptions,
  type RetryConfig,
  type SlackResponse,
  type ResponseMetadata,
  type SlackMessage,
  type SlackChannel,
  type SlackUser,
  type UserProfile,
  type Attachment,
  type MessageMetadata,
  type ChatPostMessageArguments,
  type ChatPostMessageResponse,
  type ChatUpdateArguments,
  type ChatUpdateResponse,
  type ChatDeleteArguments,
  type ChatDeleteResponse,
  type ConversationsListArguments,
  type ConversationsListResponse,
  type ConversationsHistoryArguments,
  type ConversationsHistoryResponse,
  type ConversationsInfoArguments,
  type ConversationsInfoResponse,
  type ConversationsJoinArguments,
  type ConversationsJoinResponse,
  type ConversationsLeaveArguments,
  type ConversationsLeaveResponse,
  type ConversationsCreateArguments as ClientCreateArgs,
  type ConversationsCreateResponse as ClientCreateResponse,
  type ConversationsArchiveArguments as ClientArchiveArgs,
  type ConversationsArchiveResponse as ClientArchiveResponse,
  type ConversationsUnarchiveArguments as ClientUnarchiveArgs,
  type ConversationsUnarchiveResponse as ClientUnarchiveResponse,
  type ConversationsInviteArguments as ClientInviteArgs,
  type ConversationsInviteResponse as ClientInviteResponse,
  type ConversationsKickArguments as ClientKickArgs,
  type ConversationsKickResponse as ClientKickResponse,
  type ConversationsMembersArguments as ClientMembersArgs,
  type ConversationsMembersResponse as ClientMembersResponse,
  type ConversationsRenameArguments as ClientRenameArgs,
  type ConversationsRenameResponse as ClientRenameResponse,
  type ConversationsSetTopicArguments as ClientSetTopicArgs,
  type ConversationsSetTopicResponse as ClientSetTopicResponse,
  type ConversationsSetPurposeArguments as ClientSetPurposeArgs,
  type ConversationsSetPurposeResponse as ClientSetPurposeResponse,
  type ConversationsOpenArguments as ClientOpenArgs,
  type ConversationsOpenResponse as ClientOpenResponse,
  type ConversationsCloseArguments as ClientCloseArgs,
  type ConversationsCloseResponse as ClientCloseResponse,
  type ConversationsRepliesArguments as ClientRepliesArgs,
  type ConversationsRepliesResponse as ClientRepliesResponse,
  type ConversationsMarkArguments as ClientMarkArgs,
  type ConversationsMarkResponse as ClientMarkResponse,
  type UsersListArguments,
  type UsersListResponse,
  type UsersInfoArguments,
  type UsersInfoResponse,
  type UsersLookupByEmailArguments,
  type UsersLookupByEmailResponse,
  // Chat ephemeral & scheduled
  type ChatPostEphemeralArguments,
  type ChatPostEphemeralResponse,
  type ChatScheduleMessageArguments,
  type ChatScheduleMessageResponse,
  type ChatDeleteScheduledMessageArguments,
  type ChatDeleteScheduledMessageResponse,
  // Reactions
  type ReactionsAddArguments,
  type ReactionsAddResponse,
  type ReactionsRemoveArguments,
  type ReactionsRemoveResponse,
  type ReactionsGetArguments,
  type ReactionsGetResponse,
  type ReactionsListArguments,
  type ReactionsListResponse,
  type Reaction,
  type ReactedItem,
} from './client'

// Re-export from blocks
export * from './blocks'

// Re-export from messages
export {
  SlackMessages,
  createSlackMessages,
  MessageBuilder,
  message,
  SlackMessageError,
  // mrkdwn helpers
  bold,
  italic,
  strike,
  code,
  codeBlock,
  blockquote,
  link,
  mention,
  channel as mentionChannel,
  here,
  atChannel,
  everyone,
  date,
  emoji,
  numberedList,
  bulletList,
  escape,
  // types
  type MessageRef,
  type MessageMetadata as MessagesMetadata,
  type MessageContent,
  type PostMessageOptions,
  type EphemeralMessageOptions,
  type UpdateMessageOptions,
  type ScheduleMessageOptions,
  type PostMessageResponse,
  type EphemeralResponse,
  type UpdateResponse,
  type DeleteResponse,
  type ScheduleResponse,
  type SlackMessagesOptions,
} from './messages'

// Re-export types from types.ts for bolt compatibility
export type {
  Message,
  Channel,
  User,
  Block as BlockType,
  SectionBlock as SectionBlockType,
  DividerBlock as DividerBlockType,
  ImageBlock as ImageBlockType,
  ActionsBlock as ActionsBlockType,
  ContextBlock as ContextBlockType,
  InputBlock as InputBlockType,
  HeaderBlock as HeaderBlockType,
  TextObject as TextObjectType,
  ButtonElement as ButtonElementType,
  StaticSelectElement as StaticSelectElementType,
  Option as OptionType,
  SlackEvent,
  MessageEvent,
  AppMentionEvent,
  ReactionAddedEvent,
  ReactionRemovedEvent,
  BlockAction,
  BlockActionsPayload,
  ViewSubmissionPayload,
  ViewClosedPayload,
  ViewOutput,
  ViewState,
  ShortcutPayload,
  GlobalShortcutPayload,
  MessageShortcutPayload,
  SlashCommand,
  CommandResponse,
  SlackEventMiddlewareArgs,
  SlackActionMiddlewareArgs,
  SlackViewMiddlewareArgs,
  SlackShortcutMiddlewareArgs,
  SlackCommandMiddlewareArgs,
  SayFn,
  RespondFn,
  AckFn,
  NextFn,
  Middleware,
  AppOptions,
} from './types'

// Re-export App and utilities from slack.ts for bolt compatibility
export {
  App,
  _clearAll,
  _getChannels,
  _getMessages,
  generateSignature,
  verifyRequestSignature,
} from './slack'

// Re-export channel management from channels.ts
export {
  ChannelManager,
  SlackChannelError,
  normalizeChannelName,
  isPublicChannel,
  isPrivateChannel,
  isDirectMessage,
  isMultiPartyDM,
  parseUserIds,
  formatUserIds,
  type ChannelManagerOptions,
  type SlackChannel as ChannelInfo,
  type ChannelTopic,
  type ChannelPurpose,
  type ConversationsCreateArguments,
  type ConversationsCreateResponse,
  type ConversationsArchiveArguments,
  type ConversationsArchiveResponse,
  type ConversationsUnarchiveArguments,
  type ConversationsUnarchiveResponse,
  type ConversationsInviteArguments,
  type ConversationsInviteResponse,
  type ConversationsKickArguments,
  type ConversationsKickResponse,
  type ConversationsSetTopicArguments,
  type ConversationsSetTopicResponse,
  type ConversationsSetPurposeArguments,
  type ConversationsSetPurposeResponse,
  type ConversationsMembersArguments,
  type ConversationsMembersResponse,
  type ConversationsRenameArguments,
  type ConversationsRenameResponse,
  type ConversationsMarkArguments,
  type ConversationsMarkResponse,
  type ConversationsOpenArguments,
  type ConversationsOpenResponse,
  type ConversationsCloseArguments,
  type ConversationsCloseResponse,
  type ConversationsRepliesArguments,
  type ConversationsRepliesResponse,
} from './channels'

// Re-export slash commands from slash-commands.ts
export {
  SlashCommands,
  SlashCommandError,
  parseArgs,
  verifySignature,
  commandResponse,
  ephemeral,
  inChannel,
  type ParsedArgs,
  type CommandContext,
  type CommandHandler,
  type CommandDefinition,
  type ArgConfig,
  type SlashCommandsOptions,
  type DelayedResponseOptions,
} from './slash-commands'

// Re-export bot framework
export {
  SlackBot,
  BotWebClient,
  OAuthFlow,
  OAuthError,
  SocketModeClient,
  type SlackBotOptions,
  type Logger as BotLogger,
  type AuthorizeFn,
  type AuthorizeSourceData,
  type AuthorizeResult,
  type BotInfo,
  type AppHomeOpenedEvent,
  type ChannelArchiveEvent,
  type ChannelUnarchiveEvent,
  type ChannelRenameEvent,
  type UserChangeEvent,
  type TeamJoinEvent,
  type FileSharedEvent,
  type PinAddedEvent,
  type PinRemovedEvent,
  type BotEvent,
  type BotEventType,
  type BotMiddlewareArgs,
  type BotContext,
  type BotEventArgs,
  type BotMessageArgs,
  type BotActionArgs,
  type BotViewArgs,
  type ViewAckResponse,
  type BotShortcutArgs,
  type BotCommandArgs,
  type ViewsMethods,
  type ViewsOpenArguments,
  type ViewsPushArguments,
  type ViewsUpdateArguments,
  type ViewsPublishArguments,
  type ModalView,
  type HomeView,
  type ViewsOpenResponse,
  type ViewsPushResponse,
  type ViewsUpdateResponse,
  type ViewsPublishResponse,
  // ReactionsMethods interface exported from bot.ts for typing (not the class from client.ts)
  type ReactionsMethods as BotReactionsMethods,
  // Reactions types already exported from client.ts, just export the unique ones from bot
  type ReactionsResponse,
  type ReactionItem,
  type AuthMethods,
  type AuthTestResponse,
  type AuthRevokeArguments,
  type AuthRevokeResponse,
  type OAuthConfig,
  type InstallationStore,
  type StateStore,
  type Installation,
  type InstallationQuery,
  type InstallUrlOptions,
  type SocketModeEvent,
} from './bot'

// Re-export App Home management
export {
  AppHome,
  AppHomeError,
  createAppHome,
  HomeTabBuilder,
  ModalBuilder,
  // Value extraction utilities
  extractTextValue,
  extractSelectValue,
  extractMultiSelectValues,
  extractUserValue,
  extractMultiUserValues,
  extractChannelValue,
  extractMultiChannelValues,
  extractConversationValue,
  extractDateValue,
  extractTimeValue,
  extractAllValues,
  // Types
  type AppHomeConfig,
  type DefaultHomeTabConfig,
  type PublishHomeTabArgs,
  type OpenModalArgs,
  type PushModalArgs,
  type UpdateModalArgs,
  type HomeTabViewType,
  type ModalViewType,
  type ShortcutContext,
  type MessageShortcutContext,
  type ViewSubmissionContext,
  type ViewSubmissionResponse,
  type ViewClosedContext,
  type ShortcutHandler as AppHomeShortcutHandler,
  type MessageShortcutHandler,
  type ViewSubmissionHandler,
  type ViewClosedHandler,
  type AppHomeOpenedContext,
  type AppHomeOpenedHandler,
  type HomeTabConfig,
  type ModalConfig,
  type ShortcutConfig,
  type HomeTabContext,
} from './app-home'

// Re-export workflows
export {
  WorkflowBuilder,
  WorkflowStep,
  WorkflowTrigger,
  WorkflowClient,
  createWorkflow,
  createWorkflowStep,
  type WorkflowDefinition,
  type WorkflowStepConfig,
  type WorkflowInput,
  type WorkflowOutput,
  type WorkflowEditArgs,
  type WorkflowSaveArgs,
  type WorkflowExecuteArgs,
  type WorkflowStepEditPayload,
  type WorkflowStepSavePayload,
  type WorkflowStepExecutePayload,
  type WorkflowStepOutput,
  type TriggerType,
  type TriggerConfig,
  type ScheduledTrigger,
  type WebhookTrigger,
  type EventTrigger,
  type ScheduleConfig,
  type TriggerResponse,
  type TriggersListResponse,
  type TriggerUpdateArgs,
  type TriggerDeleteArgs,
  type ConfigureFn,
  type UpdateFn,
  type CompleteFn,
  type FailFn,
  type StepCompletedArgs,
  type StepFailedArgs,
  type StepUpdateArgs,
  type WorkflowPublishResponse,
  type WorkflowDeleteResponse,
  type WorkflowListResponse,
  type WorkflowInfoResponse,
  type APIResponse,
} from './workflows'

// Default export
export { WebClient as default } from './client'
