/**
 * Test Data Factories for @dotdo
 *
 * This module provides factory functions for creating test data.
 * These factories create valid data structures for Things, Events,
 * Relationships, and other domain objects.
 *
 * @module test-utils/factories
 */

import { generateTestId } from './helpers'
import type { Thing, Event, Relationship } from './assertions'

// Re-export types for convenience
export type { Thing, Event, Relationship }

// ============================================================================
// Thing Factories
// ============================================================================

/**
 * Input data for creating a Thing.
 * Mirrors the structure expected by things.create()
 */
export interface ThingInput {
  $type: string
  [key: string]: unknown
}

/**
 * Create a Thing input object for testing.
 *
 * Generates valid input data for creating a Thing via the things store.
 * Does not include system fields ($id, $createdAt, $updatedAt) as those
 * are generated by the store.
 *
 * @param overrides - Fields to override or add
 * @returns A valid ThingInput object
 *
 * @example
 * ```typescript
 * // Create a Customer input
 * const customerInput = createThingInput({ $type: 'Customer', name: 'Alice' })
 * const customer = await things.create(customerInput)
 *
 * // Create with defaults
 * const defaultInput = createThingInput()
 * // { $type: 'TestThing' }
 * ```
 */
export function createThingInput(overrides: Partial<ThingInput> = {}): ThingInput {
  return {
    $type: 'TestThing',
    ...overrides
  }
}

/**
 * Create a complete Thing object for testing.
 *
 * Generates a complete Thing including system fields.
 * Useful for mocking or testing code that expects complete Things.
 *
 * @param overrides - Fields to override
 * @returns A complete Thing object
 *
 * @example
 * ```typescript
 * const customer = createThing({ $type: 'Customer', name: 'Alice' })
 * expect(customer.$id).toBeDefined()
 * expect(customer.$createdAt).toBeLessThanOrEqual(Date.now())
 * ```
 */
export function createThing(overrides: Partial<Thing> = {}): Thing {
  const now = Date.now()
  return {
    $id: generateTestId('thing'),
    $type: 'TestThing',
    $createdAt: now,
    $updatedAt: now,
    ...overrides
  }
}

/**
 * Create multiple Thing input objects for testing.
 *
 * @param count - Number of Things to create
 * @param baseOverrides - Base overrides for all Things
 * @param customizer - Optional function to customize each Thing
 * @returns Array of ThingInput objects
 *
 * @example
 * ```typescript
 * const inputs = createThingInputs(3, { $type: 'Customer' }, (i) => ({
 *   name: `Customer ${i + 1}`
 * }))
 * // [
 * //   { $type: 'Customer', name: 'Customer 1' },
 * //   { $type: 'Customer', name: 'Customer 2' },
 * //   { $type: 'Customer', name: 'Customer 3' }
 * // ]
 * ```
 */
export function createThingInputs(
  count: number,
  baseOverrides: Partial<ThingInput> = {},
  customizer?: (index: number) => Partial<ThingInput>
): ThingInput[] {
  return Array.from({ length: count }, (_, i) =>
    createThingInput({
      ...baseOverrides,
      ...(customizer ? customizer(i) : {})
    })
  )
}

// ============================================================================
// Event Factories
// ============================================================================

/**
 * Input data for emitting an Event.
 */
export interface EventInput {
  type: string
  payload?: unknown
}

/**
 * Create an Event input object for testing.
 *
 * @param overrides - Fields to override
 * @returns A valid EventInput object
 *
 * @example
 * ```typescript
 * const eventInput = createEventInput({
 *   type: 'Order.placed',
 *   payload: { orderId: '123', total: 99.99 }
 * })
 * const event = await events.emit(eventInput)
 * ```
 */
export function createEventInput(overrides: Partial<EventInput> = {}): EventInput {
  return {
    type: 'Test.event',
    payload: {},
    ...overrides
  }
}

/**
 * Create a complete Event object for testing.
 *
 * @param overrides - Fields to override
 * @returns A complete Event object
 *
 * @example
 * ```typescript
 * const event = createEvent({
 *   type: 'Customer.created',
 *   payload: { name: 'Alice' }
 * })
 * expectValidEvent(event)
 * ```
 */
export function createEvent(overrides: Partial<Event> = {}): Event {
  return {
    $id: generateTestId('evt'),
    type: 'Test.event',
    payload: {},
    $timestamp: Date.now(),
    ...overrides
  }
}

/**
 * Create multiple Event input objects for testing.
 *
 * @param count - Number of Events to create
 * @param baseOverrides - Base overrides for all Events
 * @param customizer - Optional function to customize each Event
 * @returns Array of EventInput objects
 *
 * @example
 * ```typescript
 * const events = createEventInputs(5, { type: 'Order.placed' }, (i) => ({
 *   payload: { orderId: `order-${i}`, total: (i + 1) * 10 }
 * }))
 * ```
 */
export function createEventInputs(
  count: number,
  baseOverrides: Partial<EventInput> = {},
  customizer?: (index: number) => Partial<EventInput>
): EventInput[] {
  return Array.from({ length: count }, (_, i) =>
    createEventInput({
      ...baseOverrides,
      ...(customizer ? customizer(i) : {})
    })
  )
}

// ============================================================================
// Relationship Factories
// ============================================================================

/**
 * Input data for creating a Relationship.
 */
export interface RelationshipInput {
  subject: string
  predicate: string
  object: string
  metadata?: Record<string, unknown>
}

/**
 * Create a Relationship input object for testing.
 *
 * @param overrides - Fields to override
 * @returns A valid RelationshipInput object
 *
 * @example
 * ```typescript
 * const relInput = createRelationshipInput({
 *   subject: 'user-1',
 *   predicate: 'owns',
 *   object: 'order-1'
 * })
 * const rel = await relationships.add(relInput)
 * ```
 */
export function createRelationshipInput(
  overrides: Partial<RelationshipInput> = {}
): RelationshipInput {
  return {
    subject: generateTestId('subject'),
    predicate: 'relates-to',
    object: generateTestId('object'),
    ...overrides
  }
}

/**
 * Create a complete Relationship object for testing.
 *
 * @param overrides - Fields to override
 * @returns A complete Relationship object
 *
 * @example
 * ```typescript
 * const rel = createRelationship({
 *   subject: 'user-1',
 *   predicate: 'owns',
 *   object: 'order-1'
 * })
 * expectValidRelationship(rel)
 * ```
 */
export function createRelationship(overrides: Partial<Relationship> = {}): Relationship {
  return {
    subject: generateTestId('subject'),
    predicate: 'relates-to',
    object: generateTestId('object'),
    $createdAt: Date.now(),
    ...overrides
  }
}

/**
 * Create multiple Relationship input objects for testing.
 *
 * @param count - Number of Relationships to create
 * @param baseOverrides - Base overrides for all Relationships
 * @param customizer - Optional function to customize each Relationship
 * @returns Array of RelationshipInput objects
 *
 * @example
 * ```typescript
 * // Create relationships from one user to multiple orders
 * const rels = createRelationshipInputs(3, {
 *   subject: 'user-1',
 *   predicate: 'owns'
 * }, (i) => ({
 *   object: `order-${i + 1}`
 * }))
 * ```
 */
export function createRelationshipInputs(
  count: number,
  baseOverrides: Partial<RelationshipInput> = {},
  customizer?: (index: number) => Partial<RelationshipInput>
): RelationshipInput[] {
  return Array.from({ length: count }, (_, i) =>
    createRelationshipInput({
      ...baseOverrides,
      ...(customizer ? customizer(i) : {})
    })
  )
}

// ============================================================================
// Domain-Specific Factories
// ============================================================================

/**
 * Create a Customer Thing input for testing.
 *
 * @param overrides - Fields to override
 * @returns A Customer ThingInput
 *
 * @example
 * ```typescript
 * const customer = createCustomerInput({ name: 'Alice', email: 'alice@example.com' })
 * const created = await things.create(customer)
 * ```
 */
export function createCustomerInput(
  overrides: Partial<ThingInput & { name?: string; email?: string; status?: string }> = {}
): ThingInput {
  return createThingInput({
    $type: 'Customer',
    name: `Customer-${generateTestId('name').slice(-6)}`,
    email: `test-${Date.now()}@example.com`,
    status: 'active',
    ...overrides
  })
}

/**
 * Create an Order Thing input for testing.
 *
 * @param overrides - Fields to override
 * @returns An Order ThingInput
 *
 * @example
 * ```typescript
 * const order = createOrderInput({ total: 99.99, items: ['item-1', 'item-2'] })
 * const created = await things.create(order)
 * ```
 */
export function createOrderInput(
  overrides: Partial<ThingInput & { total?: number; items?: string[]; status?: string }> = {}
): ThingInput {
  return createThingInput({
    $type: 'Order',
    total: Math.floor(Math.random() * 1000) + 1,
    items: [],
    status: 'pending',
    ...overrides
  })
}

/**
 * Create a User Thing input for testing.
 *
 * @param overrides - Fields to override
 * @returns A User ThingInput
 *
 * @example
 * ```typescript
 * const user = createUserInput({ name: 'Alice', roles: ['admin'] })
 * const created = await things.create(user)
 * ```
 */
export function createUserInput(
  overrides: Partial<ThingInput & { name?: string; email?: string; roles?: string[] }> = {}
): ThingInput {
  const id = generateTestId('user').slice(-6)
  return createThingInput({
    $type: 'User',
    name: `User-${id}`,
    email: `user-${id}@example.com`,
    roles: ['user'],
    ...overrides
  })
}

// ============================================================================
// Batch Creation Helpers
// ============================================================================

/**
 * Create a batch of related test data.
 *
 * Generates a set of Things and Relationships that are interconnected.
 * Useful for testing complex scenarios involving multiple entities.
 *
 * @param options - Configuration for the batch
 * @returns Object containing inputs for Things and Relationships
 *
 * @example
 * ```typescript
 * const batch = createTestBatch({
 *   customers: 2,
 *   ordersPerCustomer: 3
 * })
 *
 * // Create customers
 * const customers = await things.bulkCreate(batch.customers)
 *
 * // Create orders
 * const orders = await things.bulkCreate(batch.orders)
 *
 * // Create relationships
 * for (const rel of batch.relationships) {
 *   await relationships.add(rel)
 * }
 * ```
 */
export function createTestBatch(options: {
  customers?: number
  ordersPerCustomer?: number
} = {}): {
  customers: ThingInput[]
  orders: ThingInput[]
  relationships: RelationshipInput[]
} {
  const { customers: customerCount = 2, ordersPerCustomer = 2 } = options

  const customers: ThingInput[] = []
  const orders: ThingInput[] = []
  const relationships: RelationshipInput[] = []

  for (let c = 0; c < customerCount; c++) {
    const customerId = `customer-${c + 1}`
    customers.push(createCustomerInput({ name: `Customer ${c + 1}` }))

    for (let o = 0; o < ordersPerCustomer; o++) {
      const orderId = `order-${c + 1}-${o + 1}`
      orders.push(createOrderInput({ total: (c + 1) * 100 + (o + 1) * 10 }))
      relationships.push(createRelationshipInput({
        subject: customerId,
        predicate: 'placed',
        object: orderId
      }))
    }
  }

  return { customers, orders, relationships }
}
