/**
 * Generate Command
 *
 * Fetches types from connected DO and writes to .do/types.d.ts
 */

import { Command } from 'commander'
import { mkdirSync, existsSync, writeFileSync } from 'fs'
import { join } from 'path'
import { loadConfig } from '../utils/do-config'
import { createLogger } from '../utils/logger'

const logger = createLogger('generate')

export interface GenerateOptions {
  $id: string
  outputDir?: string
  mockTypes?: boolean  // For testing
}

/**
 * Fetch types from a DO
 */
export async function fetchTypes($id: string): Promise<string> {
  const typesUrl = `${$id}/.do/types.d.ts`

  try {
    const response = await fetch(typesUrl)
    if (!response.ok) {
      throw new Error(`Failed to fetch types: ${response.status}`)
    }
    return await response.text()
  } catch (error) {
    logger.warn(`Could not fetch types from ${typesUrl}, using defaults`)
    return getDefaultTypes($id)
  }
}

/**
 * Get default types when DO doesn't expose custom types
 */
function getDefaultTypes($id: string): string {
  return `// Generated by dotdo - do not edit
// Source: ${$id}

declare module 'dotdo' {
  export namespace DO {
    export interface Config {
      $id: string
      env?: 'production' | 'staging' | 'development'
    }

    // Add your custom types here or run 'dotdo generate'
    // after the DO exposes types at /.do/types.d.ts
  }
}
`
}

/**
 * Generate types and write to .do/types.d.ts
 */
export async function generateTypes(options: GenerateOptions): Promise<void> {
  const { $id, outputDir = process.cwd(), mockTypes = false } = options

  const doDir = join(outputDir, '.do')
  const typesPath = join(doDir, 'types.d.ts')

  // Create .do directory
  if (!existsSync(doDir)) {
    mkdirSync(doDir, { recursive: true })
  }

  // Fetch or mock types
  const types = mockTypes ? getDefaultTypes($id) : await fetchTypes($id)

  // Write types file
  writeFileSync(typesPath, types, 'utf-8')
  logger.success(`Types written to ${typesPath}`)
}

/**
 * Commander command for 'dotdo generate'
 */
export const generateCommand = new Command('generate')
  .description('Generate types from connected DO')
  .option('-d, --dir <dir>', 'Output directory', process.cwd())
  .action(async (options) => {
    const config = await loadConfig(options.dir)

    if (!config) {
      logger.error('No do.config.ts found. Run "dotdo connect" first.')
      process.exit(1)
    }

    await generateTypes({
      $id: config.$id,
      outputDir: options.dir
    })
  })

export default generateCommand
