/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OperatorImport } from './routes/operator'
import { Route as DocsImport } from './routes/docs'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as DocsSplatImport } from './routes/docs/$'
import { Route as AdminSplatImport } from './routes/admin/$'

// Create/Update Routes

const OperatorRoute = OperatorImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRoute,
} as any)

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsSplatRoute = DocsSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)

const AdminSplatRoute = AdminSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorImport
      parentRoute: typeof rootRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatImport
      parentRoute: typeof AdminImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatImport
      parentRoute: typeof DocsImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/operator': typeof OperatorRoute
  '/admin/$': typeof AdminSplatRoute
  '/docs/$': typeof DocsSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/operator': typeof OperatorRoute
  '/admin/$': typeof AdminSplatRoute
  '/docs/$': typeof DocsSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/operator': typeof OperatorRoute
  '/admin/$': typeof AdminSplatRoute
  '/docs/$': typeof DocsSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/docs' | '/operator' | '/admin/$' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/docs' | '/operator' | '/admin/$' | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/docs'
    | '/operator'
    | '/admin/$'
    | '/docs/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  OperatorRoute: typeof OperatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  OperatorRoute: OperatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/docs",
        "/operator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/$"
      ]
    },
    "/docs": {
      "filePath": "docs.tsx",
      "children": [
        "/docs/$"
      ]
    },
    "/operator": {
      "filePath": "operator.tsx"
    },
    "/admin/$": {
      "filePath": "admin/$.tsx",
      "parent": "/admin"
    },
    "/docs/$": {
      "filePath": "docs/$.tsx",
      "parent": "/docs"
    }
  }
}
ROUTE_MANIFEST_END */
