/**
 * Auto-generated route tree for TanStack Router
 *
 * This file is generated by TanStack Start's file-based routing.
 * In development, this is generated automatically when routes change.
 *
 * DO NOT EDIT - this file is regenerated when routes change.
 *
 * @see https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing
 */
import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as DocsRoute } from './routes/docs'

/**
 * Type-safe route path declarations
 */
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/docs': {
      preLoaderRoute: typeof DocsRoute
      parentRoute: typeof rootRoute
    }
  }
}

/**
 * Route tree with all application routes
 */
const rootRouteTree = rootRoute.addChildren([
  IndexRoute,
  DocsRoute,
])

export const routeTree = rootRouteTree

/** Re-export individual routes for direct access */
export { rootRoute, IndexRoute, DocsRoute }
