/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SplatRouteImport } from './../routes/$'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as DocsSplatRouteImport } from './../routes/docs/$'
import { Route as AppAppRouteImport } from './../routes/app/_app'
import { Route as ApiSearchRouteImport } from './../routes/api/search'
import { Route as AdminAdminRouteImport } from './../routes/admin/_admin'
import { Route as AppWorkflowsIndexRouteImport } from './../routes/app/workflows/index'
import { Route as AppTasksIndexRouteImport } from './../routes/app/tasks/index'
import { Route as AppSettingsIndexRouteImport } from './../routes/app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './../routes/app/projects/index'
import { Route as AppAppIndexRouteImport } from './../routes/app/_app.index'
import { Route as AdminWorkflowsIndexRouteImport } from './../routes/admin/workflows/index'
import { Route as AdminUsersIndexRouteImport } from './../routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './../routes/admin/settings/index'
import { Route as AdminSandboxesIndexRouteImport } from './../routes/admin/sandboxes/index'
import { Route as AdminIntegrationsIndexRouteImport } from './../routes/admin/integrations/index'
import { Route as AdminBrowsersIndexRouteImport } from './../routes/admin/browsers/index'
import { Route as AdminApprovalsIndexRouteImport } from './../routes/admin/approvals/index'
import { Route as AdminActivityIndexRouteImport } from './../routes/admin/activity/index'
import { Route as AdminAdminIndexRouteImport } from './../routes/admin/_admin.index'
import { Route as AppWorkflowsNewRouteImport } from './../routes/app/workflows/new'
import { Route as AppProjectsNewRouteImport } from './../routes/app/projects/new'
import { Route as AppProjectsProjectIdRouteImport } from './../routes/app/projects/$projectId'
import { Route as AdminWorkflowsWorkflowIdRouteImport } from './../routes/admin/workflows/$workflowId'
import { Route as AdminUsersNewRouteImport } from './../routes/admin/users/new'
import { Route as AdminUsersUserIdRouteImport } from './../routes/admin/users/$userId'
import { Route as AdminSettingsSecurityRouteImport } from './../routes/admin/settings/security'
import { Route as AdminSettingsAppearanceRouteImport } from './../routes/admin/settings/appearance'
import { Route as AdminSettingsAccountRouteImport } from './../routes/admin/settings/account'
import { Route as AdminSandboxesSandboxIdRouteImport } from './../routes/admin/sandboxes/$sandboxId'
import { Route as AdminIntegrationsApiKeysRouteImport } from './../routes/admin/integrations/api-keys'
import { Route as AdminIntegrationsIntegrationIdRouteImport } from './../routes/admin/integrations/$integrationId'
import { Route as AdminBrowsersBrowserIdRouteImport } from './../routes/admin/browsers/$browserId'
import { Route as AdminApprovalsHistoryRouteImport } from './../routes/admin/approvals/history'
import { Route as AdminApprovalsApprovalIdRouteImport } from './../routes/admin/approvals/$approvalId'
import { Route as AdminActivityLogIdRouteImport } from './../routes/admin/activity/$logId'
import { Route as AdminAdminSignupRouteImport } from './../routes/admin/_admin.signup'
import { Route as AdminAdminResetPasswordRouteImport } from './../routes/admin/_admin.reset-password'
import { Route as AdminAdminLoginRouteImport } from './../routes/admin/_admin.login'
import { Route as AdminWorkflowsWorkflowIdRunsRouteImport } from './../routes/admin/workflows/$workflowId/runs'
import { Route as AdminWorkflowsWorkflowIdRunsRunIdRouteImport } from './../routes/admin/workflows/$workflowId/runs/$runId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app/_app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/app/workflows/',
  path: '/app/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/app/tasks/',
  path: '/app/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/app/projects/',
  path: '/app/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AdminWorkflowsIndexRoute = AdminWorkflowsIndexRouteImport.update({
  id: '/admin/workflows/',
  path: '/admin/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSandboxesIndexRoute = AdminSandboxesIndexRouteImport.update({
  id: '/admin/sandboxes/',
  path: '/admin/sandboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/admin/integrations/',
  path: '/admin/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrowsersIndexRoute = AdminBrowsersIndexRouteImport.update({
  id: '/admin/browsers/',
  path: '/admin/browsers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsIndexRoute = AdminApprovalsIndexRouteImport.update({
  id: '/admin/approvals/',
  path: '/admin/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: '/admin/activity/',
  path: '/admin/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/app/workflows/new',
  path: '/app/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/app/projects/new',
  path: '/app/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/app/projects/$projectId',
  path: '/app/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsWorkflowIdRoute =
  AdminWorkflowsWorkflowIdRouteImport.update({
    id: '/admin/workflows/$workflowId',
    path: '/admin/workflows/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/admin/settings/security',
  path: '/admin/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/admin/settings/appearance',
  path: '/admin/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/admin/settings/account',
  path: '/admin/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSandboxesSandboxIdRoute = AdminSandboxesSandboxIdRouteImport.update({
  id: '/admin/sandboxes/$sandboxId',
  path: '/admin/sandboxes/$sandboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsApiKeysRoute =
  AdminIntegrationsApiKeysRouteImport.update({
    id: '/admin/integrations/api-keys',
    path: '/admin/integrations/api-keys',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIntegrationsIntegrationIdRoute =
  AdminIntegrationsIntegrationIdRouteImport.update({
    id: '/admin/integrations/$integrationId',
    path: '/admin/integrations/$integrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBrowsersBrowserIdRoute = AdminBrowsersBrowserIdRouteImport.update({
  id: '/admin/browsers/$browserId',
  path: '/admin/browsers/$browserId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsHistoryRoute = AdminApprovalsHistoryRouteImport.update({
  id: '/admin/approvals/history',
  path: '/admin/approvals/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsApprovalIdRoute =
  AdminApprovalsApprovalIdRouteImport.update({
    id: '/admin/approvals/$approvalId',
    path: '/admin/approvals/$approvalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminActivityLogIdRoute = AdminActivityLogIdRouteImport.update({
  id: '/admin/activity/$logId',
  path: '/admin/activity/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminSignupRoute = AdminAdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminResetPasswordRoute = AdminAdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminWorkflowsWorkflowIdRunsRoute =
  AdminWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AdminWorkflowsWorkflowIdRoute,
  } as any)
const AdminWorkflowsWorkflowIdRunsRunIdRoute =
  AdminWorkflowsWorkflowIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AdminWorkflowsWorkflowIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/app': typeof AppAppRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/reset-password': typeof AdminAdminResetPasswordRoute
  '/admin/signup': typeof AdminAdminSignupRoute
  '/admin/activity/$logId': typeof AdminActivityLogIdRoute
  '/admin/approvals/$approvalId': typeof AdminApprovalsApprovalIdRoute
  '/admin/approvals/history': typeof AdminApprovalsHistoryRoute
  '/admin/browsers/$browserId': typeof AdminBrowsersBrowserIdRoute
  '/admin/integrations/$integrationId': typeof AdminIntegrationsIntegrationIdRoute
  '/admin/integrations/api-keys': typeof AdminIntegrationsApiKeysRoute
  '/admin/sandboxes/$sandboxId': typeof AdminSandboxesSandboxIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/workflows/$workflowId': typeof AdminWorkflowsWorkflowIdRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/approvals': typeof AdminApprovalsIndexRoute
  '/admin/browsers': typeof AdminBrowsersIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/sandboxes': typeof AdminSandboxesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workflows': typeof AdminWorkflowsIndexRoute
  '/app/': typeof AppAppIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
  '/admin/workflows/$workflowId/runs': typeof AdminWorkflowsWorkflowIdRunsRouteWithChildren
  '/admin/workflows/$workflowId/runs/$runId': typeof AdminWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/reset-password': typeof AdminAdminResetPasswordRoute
  '/admin/signup': typeof AdminAdminSignupRoute
  '/admin/activity/$logId': typeof AdminActivityLogIdRoute
  '/admin/approvals/$approvalId': typeof AdminApprovalsApprovalIdRoute
  '/admin/approvals/history': typeof AdminApprovalsHistoryRoute
  '/admin/browsers/$browserId': typeof AdminBrowsersBrowserIdRoute
  '/admin/integrations/$integrationId': typeof AdminIntegrationsIntegrationIdRoute
  '/admin/integrations/api-keys': typeof AdminIntegrationsApiKeysRoute
  '/admin/sandboxes/$sandboxId': typeof AdminSandboxesSandboxIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/workflows/$workflowId': typeof AdminWorkflowsWorkflowIdRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/approvals': typeof AdminApprovalsIndexRoute
  '/admin/browsers': typeof AdminBrowsersIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/sandboxes': typeof AdminSandboxesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workflows': typeof AdminWorkflowsIndexRoute
  '/app': typeof AppAppIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
  '/admin/workflows/$workflowId/runs': typeof AdminWorkflowsWorkflowIdRunsRouteWithChildren
  '/admin/workflows/$workflowId/runs/$runId': typeof AdminWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/app/_app': typeof AppAppRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/admin/_admin/login': typeof AdminAdminLoginRoute
  '/admin/_admin/reset-password': typeof AdminAdminResetPasswordRoute
  '/admin/_admin/signup': typeof AdminAdminSignupRoute
  '/admin/activity/$logId': typeof AdminActivityLogIdRoute
  '/admin/approvals/$approvalId': typeof AdminApprovalsApprovalIdRoute
  '/admin/approvals/history': typeof AdminApprovalsHistoryRoute
  '/admin/browsers/$browserId': typeof AdminBrowsersBrowserIdRoute
  '/admin/integrations/$integrationId': typeof AdminIntegrationsIntegrationIdRoute
  '/admin/integrations/api-keys': typeof AdminIntegrationsApiKeysRoute
  '/admin/sandboxes/$sandboxId': typeof AdminSandboxesSandboxIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/workflows/$workflowId': typeof AdminWorkflowsWorkflowIdRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/approvals/': typeof AdminApprovalsIndexRoute
  '/admin/browsers/': typeof AdminBrowsersIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/sandboxes/': typeof AdminSandboxesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workflows/': typeof AdminWorkflowsIndexRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/admin/workflows/$workflowId/runs': typeof AdminWorkflowsWorkflowIdRunsRouteWithChildren
  '/admin/workflows/$workflowId/runs/$runId': typeof AdminWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/api/search'
    | '/app'
    | '/docs/$'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/activity/$logId'
    | '/admin/approvals/$approvalId'
    | '/admin/approvals/history'
    | '/admin/browsers/$browserId'
    | '/admin/integrations/$integrationId'
    | '/admin/integrations/api-keys'
    | '/admin/sandboxes/$sandboxId'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/security'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/workflows/$workflowId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/workflows/new'
    | '/admin/'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/browsers'
    | '/admin/integrations'
    | '/admin/sandboxes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workflows'
    | '/app/'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/workflows'
    | '/admin/workflows/$workflowId/runs'
    | '/admin/workflows/$workflowId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/search'
    | '/docs/$'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/activity/$logId'
    | '/admin/approvals/$approvalId'
    | '/admin/approvals/history'
    | '/admin/browsers/$browserId'
    | '/admin/integrations/$integrationId'
    | '/admin/integrations/api-keys'
    | '/admin/sandboxes/$sandboxId'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/security'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/workflows/$workflowId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/workflows/new'
    | '/admin'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/browsers'
    | '/admin/integrations'
    | '/admin/sandboxes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workflows'
    | '/app'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/workflows'
    | '/admin/workflows/$workflowId/runs'
    | '/admin/workflows/$workflowId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin/_admin'
    | '/api/search'
    | '/app/_app'
    | '/docs/$'
    | '/admin/_admin/login'
    | '/admin/_admin/reset-password'
    | '/admin/_admin/signup'
    | '/admin/activity/$logId'
    | '/admin/approvals/$approvalId'
    | '/admin/approvals/history'
    | '/admin/browsers/$browserId'
    | '/admin/integrations/$integrationId'
    | '/admin/integrations/api-keys'
    | '/admin/sandboxes/$sandboxId'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/security'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/workflows/$workflowId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/workflows/new'
    | '/admin/_admin/'
    | '/admin/activity/'
    | '/admin/approvals/'
    | '/admin/browsers/'
    | '/admin/integrations/'
    | '/admin/sandboxes/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/workflows/'
    | '/app/_app/'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/tasks/'
    | '/app/workflows/'
    | '/admin/workflows/$workflowId/runs'
    | '/admin/workflows/$workflowId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  AppAppRoute: typeof AppAppRouteWithChildren
  DocsSplatRoute: typeof DocsSplatRoute
  AdminActivityLogIdRoute: typeof AdminActivityLogIdRoute
  AdminApprovalsApprovalIdRoute: typeof AdminApprovalsApprovalIdRoute
  AdminApprovalsHistoryRoute: typeof AdminApprovalsHistoryRoute
  AdminBrowsersBrowserIdRoute: typeof AdminBrowsersBrowserIdRoute
  AdminIntegrationsIntegrationIdRoute: typeof AdminIntegrationsIntegrationIdRoute
  AdminIntegrationsApiKeysRoute: typeof AdminIntegrationsApiKeysRoute
  AdminSandboxesSandboxIdRoute: typeof AdminSandboxesSandboxIdRoute
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminWorkflowsWorkflowIdRoute: typeof AdminWorkflowsWorkflowIdRouteWithChildren
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute
  AdminApprovalsIndexRoute: typeof AdminApprovalsIndexRoute
  AdminBrowsersIndexRoute: typeof AdminBrowsersIndexRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
  AdminSandboxesIndexRoute: typeof AdminSandboxesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWorkflowsIndexRoute: typeof AdminWorkflowsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/app/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks/': {
      id: '/app/tasks/'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/admin/workflows/': {
      id: '/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sandboxes/': {
      id: '/admin/sandboxes/'
      path: '/admin/sandboxes'
      fullPath: '/admin/sandboxes'
      preLoaderRoute: typeof AdminSandboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/browsers/': {
      id: '/admin/browsers/'
      path: '/admin/browsers'
      fullPath: '/admin/browsers'
      preLoaderRoute: typeof AdminBrowsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals/': {
      id: '/admin/approvals/'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity/': {
      id: '/admin/activity/'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/app/workflows/new': {
      id: '/app/workflows/new'
      path: '/app/workflows/new'
      fullPath: '/app/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/app/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows/$workflowId': {
      id: '/admin/workflows/$workflowId'
      path: '/admin/workflows/$workflowId'
      fullPath: '/admin/workflows/$workflowId'
      preLoaderRoute: typeof AdminWorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/admin/settings/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/admin/settings/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/admin/settings/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sandboxes/$sandboxId': {
      id: '/admin/sandboxes/$sandboxId'
      path: '/admin/sandboxes/$sandboxId'
      fullPath: '/admin/sandboxes/$sandboxId'
      preLoaderRoute: typeof AdminSandboxesSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/api-keys': {
      id: '/admin/integrations/api-keys'
      path: '/admin/integrations/api-keys'
      fullPath: '/admin/integrations/api-keys'
      preLoaderRoute: typeof AdminIntegrationsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/$integrationId': {
      id: '/admin/integrations/$integrationId'
      path: '/admin/integrations/$integrationId'
      fullPath: '/admin/integrations/$integrationId'
      preLoaderRoute: typeof AdminIntegrationsIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/browsers/$browserId': {
      id: '/admin/browsers/$browserId'
      path: '/admin/browsers/$browserId'
      fullPath: '/admin/browsers/$browserId'
      preLoaderRoute: typeof AdminBrowsersBrowserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals/history': {
      id: '/admin/approvals/history'
      path: '/admin/approvals/history'
      fullPath: '/admin/approvals/history'
      preLoaderRoute: typeof AdminApprovalsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals/$approvalId': {
      id: '/admin/approvals/$approvalId'
      path: '/admin/approvals/$approvalId'
      fullPath: '/admin/approvals/$approvalId'
      preLoaderRoute: typeof AdminApprovalsApprovalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity/$logId': {
      id: '/admin/activity/$logId'
      path: '/admin/activity/$logId'
      fullPath: '/admin/activity/$logId'
      preLoaderRoute: typeof AdminActivityLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/signup': {
      id: '/admin/_admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminAdminSignupRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/reset-password': {
      id: '/admin/_admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminAdminResetPasswordRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/login': {
      id: '/admin/_admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/workflows/$workflowId/runs': {
      id: '/admin/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/admin/workflows/$workflowId/runs'
      preLoaderRoute: typeof AdminWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AdminWorkflowsWorkflowIdRoute
    }
    '/admin/workflows/$workflowId/runs/$runId': {
      id: '/admin/workflows/$workflowId/runs/$runId'
      path: '/$runId'
      fullPath: '/admin/workflows/$workflowId/runs/$runId'
      preLoaderRoute: typeof AdminWorkflowsWorkflowIdRunsRunIdRouteImport
      parentRoute: typeof AdminWorkflowsWorkflowIdRunsRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminResetPasswordRoute: typeof AdminAdminResetPasswordRoute
  AdminAdminSignupRoute: typeof AdminAdminSignupRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminResetPasswordRoute: AdminAdminResetPasswordRoute,
  AdminAdminSignupRoute: AdminAdminSignupRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AppAppRouteChildren {
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AdminWorkflowsWorkflowIdRunsRouteChildren {
  AdminWorkflowsWorkflowIdRunsRunIdRoute: typeof AdminWorkflowsWorkflowIdRunsRunIdRoute
}

const AdminWorkflowsWorkflowIdRunsRouteChildren: AdminWorkflowsWorkflowIdRunsRouteChildren =
  {
    AdminWorkflowsWorkflowIdRunsRunIdRoute:
      AdminWorkflowsWorkflowIdRunsRunIdRoute,
  }

const AdminWorkflowsWorkflowIdRunsRouteWithChildren =
  AdminWorkflowsWorkflowIdRunsRoute._addFileChildren(
    AdminWorkflowsWorkflowIdRunsRouteChildren,
  )

interface AdminWorkflowsWorkflowIdRouteChildren {
  AdminWorkflowsWorkflowIdRunsRoute: typeof AdminWorkflowsWorkflowIdRunsRouteWithChildren
}

const AdminWorkflowsWorkflowIdRouteChildren: AdminWorkflowsWorkflowIdRouteChildren =
  {
    AdminWorkflowsWorkflowIdRunsRoute:
      AdminWorkflowsWorkflowIdRunsRouteWithChildren,
  }

const AdminWorkflowsWorkflowIdRouteWithChildren =
  AdminWorkflowsWorkflowIdRoute._addFileChildren(
    AdminWorkflowsWorkflowIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  AppAppRoute: AppAppRouteWithChildren,
  DocsSplatRoute: DocsSplatRoute,
  AdminActivityLogIdRoute: AdminActivityLogIdRoute,
  AdminApprovalsApprovalIdRoute: AdminApprovalsApprovalIdRoute,
  AdminApprovalsHistoryRoute: AdminApprovalsHistoryRoute,
  AdminBrowsersBrowserIdRoute: AdminBrowsersBrowserIdRoute,
  AdminIntegrationsIntegrationIdRoute: AdminIntegrationsIntegrationIdRoute,
  AdminIntegrationsApiKeysRoute: AdminIntegrationsApiKeysRoute,
  AdminSandboxesSandboxIdRoute: AdminSandboxesSandboxIdRoute,
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminWorkflowsWorkflowIdRoute: AdminWorkflowsWorkflowIdRouteWithChildren,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
  AdminApprovalsIndexRoute: AdminApprovalsIndexRoute,
  AdminBrowsersIndexRoute: AdminBrowsersIndexRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
  AdminSandboxesIndexRoute: AdminSandboxesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWorkflowsIndexRoute: AdminWorkflowsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
