import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/types.ts',
    'src/errors.ts',
    'src/constants.ts',
    'src/path.ts',
    'src/backend.ts',
    'src/fsx.ts',
    'src/config.ts',
    'src/glob/index.ts',
    'src/glob/match.ts',
    'src/glob/glob.ts',
    'src/grep/index.ts',
    'src/grep/grep.ts',
    'src/find/index.ts',
    'src/find/find.ts',
    'src/cas/index.ts',
    'src/cas/content-addressable-fs.ts',
    'src/cas/hash.ts',
    'src/cas/git-object.ts',
    'src/cas/compression.ts',
    'src/cas/path-mapping.ts',
    'src/cas/put-object.ts',
    'src/cas/get-object.ts',
    'src/cas/has-object.ts',
    'src/sparse/patterns.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
})
