/**
 * @dotdo/do/primitives - Extended Primitives with AI Assistance
 *
 * This module re-exports primitives from submodules:
 * - fsx: File system operations (from fsx submodule)
 * - gitx: Git operations (from gitx submodule)
 * - bashx: Bash/shell command execution (from bashx submodule)
 * - npmx: NPM/NPX operations (from npmx submodule)
 *
 * @packageDocumentation
 */

// File System Primitive (fsx submodule)
// Re-export core FSx functionality
export {
  // Core classes and types
  FSx,
  type FSxOptions,
  Stats,
  Dirent,
  FileHandle,
  MemoryBackend,
  type FsBackend,
  type BackendWriteResult,
  type BackendReadResult,
  type BackendOptions,
  constants,
  type Constants,
  // Types
  type FsCapability,
  type StorageTier,
  type FileStat,
  type StatsInit,
  type StatsLike,
  type DirentType,
  type FileType,
  type FileEntry,
  type FileMode,
  type ReadOptions,
  type WriteOptions,
  type ListOptions,
  type CopyOptions,
  type MoveOptions,
  type RemoveOptions,
  type ReadStreamOptions,
  type WriteStreamOptions,
  type MkdirOptions,
  type RmdirOptions,
  type ReaddirOptions,
  type WatchOptions,
  type WriteResult,
  type ReadResult,
  type FSWatcher,
  type BufferEncoding,
  type BlobRef,
  // Errors
  FSError,
  ENOENT,
  EEXIST,
  EISDIR,
  ENOTDIR,
  EACCES,
  EPERM,
  ENOTEMPTY,
  EBADF,
  EINVAL,
  ELOOP,
  ENAMETOOLONG,
  ENOSPC,
  EROFS,
  EBUSY,
  EMFILE,
  ENFILE,
  EXDEV,
  // Path utilities
  normalize,
  join,
  resolve,
  dirname,
  basename,
  extname,
  isAbsolute,
  relative,
  // Glob and search
  match,
  createMatcher,
  type MatchOptions,
  glob,
  GlobTimeoutError,
  GlobAbortedError,
  type GlobOptions,
  find,
  type FindOptions,
  type FindResult,
  grep,
  type GrepOptions,
  type GrepMatch,
  type GrepResult,
  // CAS
  ContentAddressableFS,
  type CASObject,
  type CASStorage,
  type ObjectType as CASObjectType,
  sha1,
  sha256,
  bytesToHex,
  hexToBytes,
  hashToPath,
  pathToHash,
  // Sparse checkout
  parsePattern,
  type ParsedPattern,
  // Config
  createConfig,
  isReadOnly,
  defaultConfig,
  type FSxConfig,
  type FSxConfigOptions,
  // DO integration
  FileSystemDO,
  FsModule,
  type FsModuleConfig,
  withFs,
  hasFs,
  getFs,
  type WithFsContext,
  type WithFsOptions,
  type WithFsDO,
  // Storage backends
  TieredFS,
  R2Storage,
  SQLiteMetadata,
  R2Backend,
  type R2BackendConfig,
  // Factory
  createFs,
  fs,
} from '../../fsx/index.js'

// Git Primitive (gitx submodule)
// Re-export core git functionality
export {
  // Types - Objects
  type ObjectType as GitObjectType,
  type GitObject,
  type BlobObject,
  type TreeObject,
  type TreeEntry,
  type CommitObject,
  type TagObject,
  type Author,
  isBlob,
  isTree,
  isCommit,
  isTag,
  // Validation
  SHA_PATTERN,
  VALID_MODES,
  isValidSha,
  isValidObjectType,
  isValidMode,
  validateTreeEntry,
  validateAuthor,
  validateCommit,
  validateTag,
  // Serialization
  serializeBlob,
  serializeTree,
  serializeCommit,
  serializeTag,
  parseBlob,
  parseTree,
  parseCommit,
  parseTag,
  // Pack operations
  PACK_SIGNATURE,
  PACK_VERSION,
  PackObjectType,
  packObjectTypeToString,
  stringToPackObjectType,
  encodeVarint,
  decodeVarint,
  encodeTypeAndSize,
  decodeTypeAndSize,
  parsePackHeader,
  parsePackObject,
  createPackfile,
  type PackHeader,
  type ParsedPackObject,
  type PackableObject,
  // Pack index
  PACK_INDEX_SIGNATURE,
  PACK_INDEX_MAGIC,
  PACK_INDEX_VERSION,
  LARGE_OFFSET_THRESHOLD,
  parsePackIndex,
  createPackIndex,
  lookupObject,
  verifyPackIndex,
  serializePackIndex,
  getFanoutRange,
  calculateCRC32,
  binarySearchObjectId,
  binarySearchSha,
  parseFanoutTable,
  readPackOffset,
  type PackIndexEntry,
  type PackIndex,
  type PackIndexLookupResult,
  type CreatePackIndexOptions,
  type PackedObject,
  // Git operations - Merge
  merge,
  findMergeBase,
  resolveConflict,
  abortMerge,
  continueMerge,
  getMergeState,
  isMergeInProgress,
  mergeContent,
  isBinaryFile,
  type ConflictType,
  type MergeStrategy,
  type MergeStatus,
  type ConflictMarker,
  type MergeConflict,
  type MergeOptions,
  type MergeStats,
  type MergeResult,
  type MergeState,
  type ResolveOptions,
  type ResolveResult,
  type MergeOperationResult,
  type MergeStorage,
  // Git operations - Blame
  blame,
  blameFile,
  blameLine,
  blameRange,
  getBlameForCommit,
  trackContentAcrossRenames,
  detectRenames,
  buildBlameHistory,
  formatBlame,
  parseBlameOutput,
  type BlameStorage,
  type BlameOptions,
  type BlameLineInfo,
  type BlameCommitInfo,
  type BlameEntry,
  type BlameResult,
  type BlameFormatOptions,
  type PathHistoryEntry,
  type BlameHistoryEntry,
  // Git operations - Commit
  createCommit,
  amendCommit,
  buildCommitObject,
  formatCommitMessage,
  parseCommitMessage,
  validateCommitMessage,
  isCommitSigned,
  extractCommitSignature,
  addSignatureToCommit,
  isEmptyCommit,
  getCurrentTimezone,
  formatTimestamp,
  parseTimestamp,
  createAuthor,
  type CommitAuthor,
  type SigningOptions,
  type CommitOptions,
  type AmendOptions,
  type FormatOptions,
  type CommitResult,
  type ObjectStore,
  // Git operations - Branch
  createBranch,
  deleteBranch,
  listBranches,
  renameBranch,
  checkoutBranch,
  getCurrentBranch,
  getBranchInfo,
  branchExists,
  setBranchTracking,
  getBranchTracking,
  removeBranchTracking,
  getDefaultBranch,
  setDefaultBranch,
  isValidBranchName,
  normalizeBranchName,
  type RefStore,
  type BranchOptions,
  type BranchCreateResult,
  type BranchDeleteOptions,
  type BranchDeleteResult,
  type BranchListOptions,
  type BranchInfo,
  type TrackingInfo,
  type BranchRenameOptions,
  type BranchRenameResult,
  type CheckoutOptions,
  type CheckoutResult,
  type SetTrackingResult,
  type RemoveTrackingResult,
  // Wire protocol
  handleInfoRefs,
  handleUploadPack,
  handleReceivePack,
  formatRefAdvertisement,
  formatUploadPackResponse,
  formatReceivePackResponse,
  parseUploadPackRequest,
  parseReceivePackRequest,
  parseCapabilities,
  capabilitiesToStrings,
  validateContentType,
  createErrorResponse,
  encodePktLine,
  decodePktLine,
  encodeFlushPkt,
  encodeDelimPkt,
  pktLineStream,
  FLUSH_PKT,
  DELIM_PKT,
  MAX_PKT_LINE_DATA,
} from '../../gitx/src/index.js'

// Git DO Integration (withGit mixin)
// Re-export DO mixins and modules for extending DOs with git capability
export {
  // Mixin for adding $.git capability
  withGit,
  hasGitCapability,
  type WithGitCapability,
  type WithGitOptions,
  type WithGitContext,
  // GitModule for direct usage
  GitModule,
  createGitModule,
  isGitModule,
  type GitModuleOptions,
  type GitBinding,
  type GitStatus,
  type SyncResult,
  type PushResult,
} from '../../gitx/src/do/index.js'

// Bash Primitive (bashx submodule)
// Re-export bash execution functionality
export {
  // Main client
  Bash,
  bash,
  type BashClientOptions,
  type BashClientExtended,
  type BashResult,
  type BashOptions,
  // Escape utilities
  shellEscape,
  shellEscapeArg,
  // Undo tracking
  UndoManager,
  createUndoManager,
  type UndoInfo,
  getUndoHistory,
  clearUndoHistory,
  setUndoOptions,
  undo,
  generateUndoInfo,
  isReversible,
  trackForUndo,
  recordUndoEntry,
  type UndoEntry,
  type UndoOptions,
  // Configuration
  type BashxConfig,
  type PartialBashxConfig,
  type CacheConfig,
  type TimeoutConfig,
  type LimitConfig,
  type ExecutionConfig,
  type RetryConfig,
  type ConfigValidationError,
  type ConfigDiffEntry,
  DEFAULT_CONFIG,
  getConfig,
  validateConfig,
  mergeConfig,
  configDiff,
} from '../../bashx/src/index.js'

// Bash DO Integration (withBash mixin)
// Re-export DO mixins and modules for extending DOs with bash capability
export {
  // Mixin for adding $.bash capability
  withBash,
  type WithBashCapability,
  type WithBashConfig,
  // BashModule for direct usage
  BashModule,
  type BashModuleOptions,
  type BashExecutor,
} from '../../bashx/src/do/index.js'

// NPM/NPX Primitive (npmx submodule)
// Re-export npm operations
export {
  // SDK
  npm,
  npx,
  createNpm,
  type NpmConfig,
  type NpmSDK,
  // CLI utilities
  createCLI,
  runCLI,
  formatPackageList,
  formatSearchResults,
  formatPackageInfo,
  formatInstallResult,
  type CommandResult,
  type PackageEntry,
  type SearchResult,
  type ListFormatOptions,
  type InstallOptions,
  // Types
  type InstallResult,
  type PackageVersion,
  type PackageUpdate,
  createEmptyInstallResult,
} from '../../npmx/index.js'
