import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { generateTypes, fetchTypes } from '../../commands/generate'
import { mkdirSync, rmSync, existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

describe('generate command', () => {
  const testDir = '/tmp/dotdo-generate-test'

  beforeEach(() => {
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('creates .do directory if not exists', async () => {
    await generateTypes({
      $id: 'https://test.example.com',
      outputDir: testDir,
      mockTypes: true  // Use mock for testing
    })

    expect(existsSync(join(testDir, '.do'))).toBe(true)
  })

  it('writes types.d.ts file', async () => {
    await generateTypes({
      $id: 'https://test.example.com',
      outputDir: testDir,
      mockTypes: true
    })

    expect(existsSync(join(testDir, '.do', 'types.d.ts'))).toBe(true)
  })

  it('includes source URL in generated types', async () => {
    await generateTypes({
      $id: 'https://test.example.com',
      outputDir: testDir,
      mockTypes: true
    })

    const content = readFileSync(join(testDir, '.do', 'types.d.ts'), 'utf-8')
    expect(content).toContain('https://test.example.com')
  })

  it('includes DO.Config interface in generated types', async () => {
    await generateTypes({
      $id: 'https://test.example.com',
      outputDir: testDir,
      mockTypes: true
    })

    const content = readFileSync(join(testDir, '.do', 'types.d.ts'), 'utf-8')
    expect(content).toContain('interface Config')
    expect(content).toContain('$id: string')
  })

  it('does not overwrite existing .do directory contents', async () => {
    // Create .do directory with an existing file
    const doDir = join(testDir, '.do')
    mkdirSync(doDir, { recursive: true })
    const existingFile = join(doDir, 'existing.txt')
    writeFileSync(existingFile, 'existing content', 'utf-8')

    await generateTypes({
      $id: 'https://test.example.com',
      outputDir: testDir,
      mockTypes: true
    })

    // Existing file should still be there
    expect(existsSync(existingFile)).toBe(true)
    expect(readFileSync(existingFile, 'utf-8')).toBe('existing content')
  })
})

describe('fetchTypes', () => {
  it('returns default types when fetch fails', async () => {
    const types = await fetchTypes('https://nonexistent.example.com')

    expect(types).toContain('Generated by dotdo')
    expect(types).toContain('interface Config')
  })

  it('includes the $id URL in default types', async () => {
    const types = await fetchTypes('https://my-do.example.com')

    expect(types).toContain('https://my-do.example.com')
  })
})
